name: Attach Debug APKs To Release

on:
  release:
    types:
      - published

jobs:
  attach-apks:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package_variant: [ apt-android-7, apt-android-5 ]

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build APKs
        shell: bash {0}
        env:
          PACKAGE_VARIANT: ${{ matrix.package_variant }}
        run: |
          set -e
          
          RELEASE_VERSION_NAME="${GITHUB_REF/refs\/tags\//}"
          
          APK_DIR_PATH="./app/build/outputs/apk/debug"
          APK_VERSION_TAG="$RELEASE_VERSION_NAME+${{ env.PACKAGE_VARIANT }}-github-debug"
          APK_BASENAME_PREFIX="termux-app_$APK_VERSION_TAG"

          echo "APK_DIR_PATH=$APK_DIR_PATH" >> $GITHUB_ENV
          echo "APK_VERSION_TAG=$APK_VERSION_TAG" >> $GITHUB_ENV
          echo "APK_BASENAME_PREFIX=$APK_BASENAME_PREFIX" >> $GITHUB_ENV

          echo "Building APKs for $APK_VERSION_TAG"
          export TERMUX_APK_VERSION_TAG="$APK_VERSION_TAG"
          export TERMUX_PACKAGE_VARIANT="${{ env.PACKAGE_VARIANT }}"
          
          ./gradlew assembleDebug

          echo "Generating sha256sums"
          (cd "$APK_DIR_PATH" && sha256sum ${APK_BASENAME_PREFIX}_*.apk > "${APK_BASENAME_PREFIX}_sha256sums")

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.APK_DIR_PATH }}/${{ env.APK_BASENAME_PREFIX }}_*.apk
            ${{ env.APK_DIR_PATH }}/${{ env.APK_BASENAME_PREFIX }}_sha256sums
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
